include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - build/**
    - lib/*.g.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
