name: flireator
description: A project creation tool for Flutter projects with a Firebase
  backend, stored on GitHub.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  sign_in_with_apple:
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
