name: flireator
description: A project creation tool for Flutter projects with a Firebase
  backend, stored on GitHub.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  built_value:
  built_collection:
  redux:
  flutter_redux:

  flutter_auth_buttons:
  sign_in_with_apple:
  firebase_auth:
  url_launcher:
  oauth2:

  # access github with a graphql client
  github_graphql_client:
    git: https://github.com/Adventures-In/github_graphql_client.git

  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  
  build_runner:
  built_value_generator:
  pedantic:
  test:
  mockito:
  redux_remote_devtools:

flutter:
  uses-material-design: true
